const CONSTANT_NOTIFICATION = {
    CUSTOMER_REQUEST_TO_DRIVER: 'CUSTOMER_REQUEST_TO_DRIVER',
    DRIVER_ACEEPT_BOOKING: 'DRIVER_ACEEPT_BOOKING',
    DRIVER_PICK_UP_CUSTOMER: 'DRIVER_PICK_UP_CUSTOMER'
}
const CONSTANT_STATUS_BOOKING = {
    FINDING_DRIVER: 'FINDING_DRIVER',
    WAITING_DRIVER: 'WAITING_DRIVER',
    PROCESSING: 'PROCESSING',
    END: 'END',
    USER_CANCEL: 'USER_CANCEL',
}
const CONSTANT_STATUS_JOUNEYS = {
    WAITING: 'WAITING',
    STARTED: 'STARTED',
    END: 'END',
    CANCEL: 'CANCEL'
}
const SERVICE_CHARGE = 0.05
const TYPE_TRANSACTION = {
    ACCEPT_BOOKING: 'ACCEPT_BOOKING'
}
module.exports = { CONSTANT_NOTIFICATION, CONSTANT_STATUS_BOOKING, CONSTANT_STATUS_JOUNEYS, SERVICE_CHARGE, TYPE_TRANSACTION }