const CONSTANT_NOTIFICATION = {
    CUSTOMER_REQUEST_TO_DRIVER: 'CUSTOMER_REQUEST_TO_DRIVER'
}
const CONSTANT_STATUS_BOOKING = {
    FINDING_DRIVER: 'FINDING_DRIVER'
}
module.exports = { CONSTANT_NOTIFICATION, CONSTANT_STATUS_BOOKING }